version: '1'

services:
  citizen-frontend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/adoption/citizen-frontend
    ports:
      - 3000:3000
  adoption-integration-tests:
    build:
      context: .
      dockerfile: integration-tests.Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/adoption/citizen-frontend-integration-tests
