version: '1'

services:
  adoption-frontend:
    image: hmctspublic.azurecr.io/adoption/frontend
    container_name: adoption-frontend
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - 3000:3000
  adoption-integration-tests:
    image: hmctspublic.azurecr.io/adoption/frontend-integration-tests
    build:
      context: .
      dockerfile: integration-tests.Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
