nodejs:
  environment:
    NODE_ENV: production
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

idam-pr:
  enabled: true
  redirect_uris:
    adoption:
      - https://www-${SERVICE_FQDN}/landing
